### ISSUE TITLE
Does not work on leaflet version 1.7.1

### ISSUE THREAD

**Issue by diego-lipinski-de-castro** [react-map/leaflet.migrationLayer#20]

**Comment by Sylvenas** [comment]
It's been a while since I've followed the updates on the leaflet, I'll check it out recently and reply.

**Comment by halfordfan** [comment]
I'm not having any issues using it with 1.7.1.

**Comment by diego-lipinski-de-castro** [comment]
@halfordfan can you link your example? Ive tried multiple ways and nothing shows, I even tried ctrl c ctrl v the examples, still nothing shows

**Comment by halfordfan** [comment]
Anything in the console log?  I'm running leaflet and this plugin under the Smashing framework; my driver is in coffeescript and available in a repo under my ID.

Edit to add:  I've created a gist using a fixed map provider of the demo linked to in the README.md file.  Look here: https://gist.github.com/halfordfan/823aeb29bbc3ba6e6946dc32acf0202b

**Comment by diego-lipinski-de-castro** [comment]
Ive tried putting your data into my app and got the folllowing

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'replacePopover')
    at new p (app.js:66829:8630)
    at NewClass._init (app.js:66829:4148)
    at NewClass.onAdd (app.js:66829:3181)
    at NewClass._layerAdd (app.js:73404:10)
    at NewClass.whenReady (app.js:71265:15)
    at NewClass.addLayer (app.js:73466:10)
    at NewClass.addTo (app.js:73342:9)
    at app.js:31193:34
    at _callee$ (app.js:23983:25)
    at tryCatch (app.js:125085:40)
```

Using the package through npm
"leaflet.migration": "^2.2.0"
"leaflet": "^1.7.1"

Maybe be worth mentioning i am use google mutant layer for tiles, not sure if that may be the problem

**Comment by diego-lipinski-de-castro** [comment]
Created a gist with the full code
I commented what could might interfere with the library

https://gist.github.com/diego-lipinski-de-castro/264b1f1b05ba7c5e088d2442428d9517
